/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.patientsBA.view;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import org.patientsBA.util.myConnection;

/**
 *
 * @author Raj Cassette
 */
public class AdminLoginForm extends javax.swing.JFrame {

    /**
     * Creates new form LoginForm
     */
    public AdminLoginForm() {
        initComponents();
        // center form
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel_User = new javax.swing.JLabel();
        jTextFieldUser = new javax.swing.JTextField();
        jPasswordFieldPsw = new javax.swing.JPasswordField();
        jCheckBoxShowPass = new javax.swing.JCheckBox();
        jButtonLogin = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jLabel_Pass1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel_Home = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin Login Form");

        jPanel2.setLayout(null);

        jLabel_User.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel_User.setIcon(new javax.swing.ImageIcon("C:\\Users\\acer\\OneDrive\\Documents\\NetBeansProjects\\Java Project Picture\\LOGIN.png")); // NOI18N
        jPanel2.add(jLabel_User);
        jLabel_User.setBounds(510, 240, 50, 50);

        jTextFieldUser.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldUser.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextFieldUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUserActionPerformed(evt);
            }
        });
        jPanel2.add(jTextFieldUser);
        jTextFieldUser.setBounds(580, 260, 230, 30);

        jPasswordFieldPsw.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPasswordFieldPsw.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPasswordFieldPsw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldPswActionPerformed(evt);
            }
        });
        jPanel2.add(jPasswordFieldPsw);
        jPasswordFieldPsw.setBounds(580, 330, 230, 30);

        jCheckBoxShowPass.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBoxShowPass.setText("Show");
        jCheckBoxShowPass.setAlignmentX(0.5F);
        jCheckBoxShowPass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jCheckBoxShowPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxShowPassActionPerformed(evt);
            }
        });
        jPanel2.add(jCheckBoxShowPass);
        jCheckBoxShowPass.setBounds(830, 330, 80, 30);

        jButtonLogin.setBackground(new java.awt.Color(0, 153, 0));
        jButtonLogin.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButtonLogin.setForeground(new java.awt.Color(240, 240, 240));
        jButtonLogin.setText("Login");
        jButtonLogin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonLogin);
        jButtonLogin.setBounds(580, 380, 100, 30);

        jButtonCancel.setBackground(new java.awt.Color(255, 0, 0));
        jButtonCancel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButtonCancel.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCancel.setText("Cancel");
        jButtonCancel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonCancel);
        jButtonCancel.setBounds(720, 380, 90, 30);

        jLabel_Pass1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel_Pass1.setIcon(new javax.swing.ImageIcon("C:\\Users\\acer\\OneDrive\\Documents\\NetBeansProjects\\Java Project Picture\\PASSWORD.png")); // NOI18N
        jPanel2.add(jLabel_Pass1);
        jLabel_Pass1.setBounds(510, 310, 50, 60);

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel2.setText("Admin Login ");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(550, 160, 290, 60);

        jLabel_Home.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_Home.setIcon(new javax.swing.ImageIcon("C:\\Users\\acer\\OneDrive\\Documents\\NetBeansProjects\\Java Project Picture\\home.png")); // NOI18N
        jLabel_Home.setText("Home");
        jLabel_Home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_HomeMouseClicked(evt);
            }
        });
        jPanel2.add(jLabel_Home);
        jLabel_Home.setBounds(20, 70, 80, 40);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\acer\\OneDrive\\Documents\\NetBeansProjects\\Java Project Picture\\adminpanelupdate.png")); // NOI18N
        jPanel2.add(jLabel1);
        jLabel1.setBounds(0, 0, 1380, 580);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1247, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginActionPerformed
        // TODO add your handling code here:
         //String combodata = jUserType.getSelectedItem.toString();
        Connection con = myConnection.getConnection();
        PreparedStatement ps;
        ResultSet rs;
        try {
            String sql="select Username, Password, Id  from admin where Username = ? and Password = ?";
            ps = con.prepareStatement(sql);
            ps.setString(1,jTextFieldUser.getText());
            ps.setString(2,String.valueOf(jPasswordFieldPsw.getPassword())); 
            //ps.setString(3,jUserType.getText()); 
            rs=ps.executeQuery();
            if(rs.next()){
                //to get the current userid
               // MyContactsForm.currentUserId=rs.getInt("id");
                //System.out.println(rs.getInt("id")+"From login");
                 ReceptionistFormFrame.currentUserId=rs.getInt("id");
                 PatientFormFrame.currentuserid=rs.getInt("id");
                 DoctorFormFrame.cuid=rs.getInt("id");
               // System.out.println(rs.getInt("id")+" From login");
                    AdminMainFrame af= new AdminMainFrame();
                    af.setVisible(true); 
                    af.pack();
                    af.setLocationRelativeTo(null);
                    af.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                    af.jLabel_User.setText(rs.getString(1));
                    this.dispose();  
            }
            else{
                JOptionPane.showMessageDialog(null,"Login error");
            }
        }
        catch(Exception ex){
            System.out.println(ex);
        }
    }//GEN-LAST:event_jButtonLoginActionPerformed

    private void jCheckBoxShowPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxShowPassActionPerformed
        // TODO add your handling code here:
        if(jCheckBoxShowPass.isSelected()){
            jPasswordFieldPsw.setEchoChar((char)0);
        }
        else{
            jPasswordFieldPsw.setEchoChar('*');
        }
    }//GEN-LAST:event_jCheckBoxShowPassActionPerformed

    private void jPasswordFieldPswActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldPswActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldPswActionPerformed

    private void jTextFieldUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUserActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        // TODO add your handling code here:
          System.exit(0);
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jLabel_HomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_HomeMouseClicked
        // TODO add your handling code here:
       Home ho= new Home();
       ho.setVisible(true);
       ho.pack();
       ho.setLocationRelativeTo(null);
       ho.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
       this.dispose();
    }//GEN-LAST:event_jLabel_HomeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminLoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminLoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminLoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminLoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminLoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonLogin;
    private javax.swing.JCheckBox jCheckBoxShowPass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel_Home;
    private javax.swing.JLabel jLabel_Pass1;
    private javax.swing.JLabel jLabel_User;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordFieldPsw;
    private javax.swing.JTextField jTextFieldUser;
    // End of variables declaration//GEN-END:variables
}
