/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.patientsBA.view;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.patientsBA.util.myConnection;

/**
 *
 * @author acer
 */
public class ChooseDoctor extends javax.swing.JInternalFrame {

    Connection connection = null;
    PreparedStatement ps = null;
    ResultSet rs = null;
    Appointment appmf;
    Appointment apprmf;
    /**
     * Creates new form ChooseDoctor
     */
    DefaultTableModel defaultTableModel = new DefaultTableModel();
    
    public ChooseDoctor() {
        initComponents();
        Object columns[] = {"Id", "Name","Address", "Gender", "Age", "Contact", "Marital", "JoiningDate", "DoctorType", "Username"};
        defaultTableModel.setColumnIdentifiers(columns);
        jTable_DP.setModel(defaultTableModel);
    }
    
    public void getAPPMF(Appointment appmf){
        this.appmf=appmf;
    }

    public void getAPPRMF(Appointment apprmf){
        this.apprmf=apprmf;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_DP = new javax.swing.JTable();
        dSearchbox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jButton_Search = new javax.swing.JButton();
        jButton_Next = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel_Back = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jTable_DP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable_DP);

        dSearchbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Doctor-Type", "General Physician", "Gynecologist", "Surgeon", "Cardiologist", "Nephrologist", "Neurologist" }));
        dSearchbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dSearchboxActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Doctor Type");

        jButton_Search.setText("Search");
        jButton_Search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_SearchMouseClicked(evt);
            }
        });
        jButton_Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SearchActionPerformed(evt);
            }
        });

        jButton_Next.setText("Next");
        jButton_Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_NextActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Select a doctor and click next");

        jLabel_Back.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_Back.setText("Back");
        jLabel_Back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_Back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_BackMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_Next)
                .addGap(480, 480, 480))
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_Back)
                        .addGap(40, 40, 40)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(dSearchbox, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jButton_Search)))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dSearchbox, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel_Back))))
                .addGap(18, 43, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_Next, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dSearchboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dSearchboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dSearchboxActionPerformed

    private void jButton_SearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_SearchMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_SearchMouseClicked

    private void jButton_SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SearchActionPerformed
        // TODO add your handling code here:
        Connection con=myConnection.getConnection();
        defaultTableModel.getDataVector().removeAllElements();
        defaultTableModel.fireTableDataChanged();
        String searchKey = (String) dSearchbox.getSelectedItem();
        String sql = "select id,name,address,gender,age,contact,marital,joiningdate,doctortype,username from doctor where doctortype = ?";
        try {
            ps = con.prepareStatement(sql);
            ps.setString(1,searchKey);
            rs = ps.executeQuery();
            Object columnData[] = new Object[10];
            while (rs.next()) {
                columnData[0] = rs.getInt("id");
                columnData[1] = rs.getString("name");
                columnData[2] = rs.getString("address");
                columnData[3] = rs.getString("gender");
                columnData[4] = rs.getInt("age");
                columnData[5] = rs.getString("contact");
                columnData[6] = rs.getString("marital");
                columnData[7] = rs.getString("joiningdate");
                columnData[8] = rs.getString("doctortype");
                columnData[9] = rs.getString("username");
                defaultTableModel.addRow(columnData);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton_SearchActionPerformed

    private void jButton_NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_NextActionPerformed
        // TODO add your handling code here:
        int row = jTable_DP.getSelectedRow();
        if(row == -1){
            JOptionPane.showMessageDialog(null,"Please select any one record!!!!!");
            return;
        }
        String id = (jTable_DP.getValueAt(row, 0).toString().trim());
        String dname = (jTable_DP.getValueAt(row, 1).toString().trim());
//        System.out.println(id);
        //System.out.println(dname);
        this.dispose();
        ChoosePatient cPatient = new ChoosePatient();
        cPatient.id = id;
        cPatient.dName = dname;
        //jDesktopPane1.add(cPatient);
//        cPatient.getCAMF(amf);
        if(appmf != null){
        appmf.amf.jDesktopPane1.add(cPatient);
        }
        else{
        apprmf.rmf.jDesktopPane1.add(cPatient);
        }
        cPatient.setVisible(true);
        
    }//GEN-LAST:event_jButton_NextActionPerformed

    private void jLabel_BackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_BackMouseClicked
        // TODO add your handling code here:
        Appointment app= new Appointment();
        appmf.amf.jDesktopPane1.add(app);
        app.setVisible(true);
    }//GEN-LAST:event_jLabel_BackMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> dSearchbox;
    private javax.swing.JButton jButton_Next;
    private javax.swing.JButton jButton_Search;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel_Back;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_DP;
    // End of variables declaration//GEN-END:variables
}
