/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.patientsBA.view;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import org.patientsBA.util.myConnection;

/**
 *
 * @author acer
 */
public class ChoosePatient extends javax.swing.JInternalFrame {
    
    ResultSet rs = null;
    PreparedStatement ps = null;
    public static String id;
    public int pid;
    public static String dName;
    DefaultTableModel defaultTableModel = new DefaultTableModel();
//    ChooseDoctor camf;
    /**
     * Creates new form ChoosePatient
     */
    public ChoosePatient() {
        initComponents();
        Object columns[] = {"Id", "Name", "Address", "Gender", "Age", "Contact", "Marital", "Register Date"};
        defaultTableModel.setColumnIdentifiers(columns);
        jTable_P.setModel(defaultTableModel);
    }

//    public void getCAMF(ChooseDoctor camf){
//        this.camf=camf;
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        SearchField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_P = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton_Search = new javax.swing.JButton();
        jButton_Next = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jDateChooser = new com.toedter.calendar.JDateChooser();
        jTextField_Time = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jRadioButton_On = new javax.swing.JRadioButton();
        jRadioButton_Off = new javax.swing.JRadioButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        SearchField.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        SearchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchFieldActionPerformed(evt);
            }
        });
        SearchField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                SearchFieldKeyPressed(evt);
            }
        });

        jTable_P.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable_P);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Id of the patient");

        jButton_Search.setText("Search");
        jButton_Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SearchActionPerformed(evt);
            }
        });

        jButton_Next.setText("Next");
        jButton_Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_NextActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Date");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Time");

        jDateChooser.setDateFormatString("yyyy-MM-d");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Status");

        buttonGroup1.add(jRadioButton_On);
        jRadioButton_On.setText("On");
        jRadioButton_On.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_OnActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton_Off);
        jRadioButton_Off.setText("Off");
        jRadioButton_Off.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_OffActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(44, 44, 44)
                                .addComponent(SearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(jButton_Search))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4))
                                        .addGap(39, 39, 39)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jRadioButton_On)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                                                .addComponent(jRadioButton_Off)
                                                .addGap(60, 60, 60))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jTextField_Time, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(0, 0, Short.MAX_VALUE))))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(475, 475, 475)
                        .addComponent(jButton_Next, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(240, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_Time, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jRadioButton_On)
                    .addComponent(jRadioButton_Off))
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jButton_Next, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SearchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchFieldActionPerformed

    private void SearchFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SearchFieldKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchFieldKeyPressed

    private void jButton_SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SearchActionPerformed
        // TODO add your handling code here:
        Connection con = myConnection.getConnection();
        defaultTableModel.getDataVector().removeAllElements();
        defaultTableModel.fireTableDataChanged();
        if(SearchField.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please insert patient id !!!!!");
            return;
        }
        int searchKey = Integer.parseInt(SearchField.getText());
        String sql = "select id,name,address,gender,age,contact,marital,registerdate from patient where id = ?";
        try {
            ps = con.prepareStatement(sql);
            ps.setInt(1,searchKey);
            rs = ps.executeQuery();
            
            Object columnData[] = new Object[8];
            while (rs.next()) {
                columnData[0] = rs.getInt("id");
                columnData[1] = rs.getString("name");
                columnData[2] = rs.getString("address");
                columnData[3] = rs.getString("gender");
                columnData[4] = rs.getInt("age");
                columnData[5] = rs.getString("contact");
                columnData[6] = rs.getString("marital");
                columnData[7] = rs.getString("registerdate");
                pid=rs.getInt("id");
                defaultTableModel.addRow(columnData);

            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton_SearchActionPerformed

    private void jButton_NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_NextActionPerformed
        // TODO add your handling code here:
        int row = jTable_P.getSelectedRow();
        if(row == -1){
            JOptionPane.showMessageDialog(null,"Please select any one record !!!!!");
            return;
        }
        String pname = (jTable_P.getValueAt(row, 1).toString().trim());
        String rdate=((JTextField)jDateChooser.getDateEditor().getUiComponent()).getText();
        String time = jTextField_Time.getText().trim();
//        jRadioButton_On.setActionCommand("On");
//        jRadioButton_Off.setActionCommand("Off");
//        String status = buttonGroup1.getSelection().getActionCommand();
        String status="";
        if(jRadioButton_On.isSelected()){
             status="On";
        }
        else if(jRadioButton_Off.isSelected()){
             status="Off";
        }
        if(rdate.equals("") || time.equals("") || status.equals("")){
            JOptionPane.showMessageDialog(null,"One or more fields are empty !!!!!");
            return;
        }
        //System.out.println(dName + "." + pname + "." + rdate + "." + time);
        try {
        Connection con = myConnection.getConnection();
        String sql = "insert into appointment(doctorName,patientName,appointmentDate,time,status,d_id,p_id) values (?,?,?,?,?,?,?)";
            ps = con.prepareStatement(sql);
            ps.setString(1, dName);
            ps.setString(2, pname);
            ps.setString(3, rdate);
            ps.setString(4, time);
            ps.setString(5, status);
            ps.setString(6, id);
            ps.setInt(7, pid);
            ps.execute();
            JOptionPane.showMessageDialog(null, "PATIENT " + pname + " Appointmented with DOCTOR " + dName + " at " + time + " in " + rdate);
//            Appointment app= new Appointment();
//            app.id=id;
//            app.setVisible(true);
        } catch (HeadlessException | SQLException e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton_NextActionPerformed

    private void jRadioButton_OnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_OnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton_OnActionPerformed

    private void jRadioButton_OffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_OffActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton_OffActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField SearchField;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton_Next;
    private javax.swing.JButton jButton_Search;
    private com.toedter.calendar.JDateChooser jDateChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton jRadioButton_Off;
    private javax.swing.JRadioButton jRadioButton_On;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_P;
    private javax.swing.JTextField jTextField_Time;
    // End of variables declaration//GEN-END:variables

    void getCAMF(AdminMainFrame amf) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
