/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.patientsBA.view;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import org.patientsBA.util.myConnection;

/**
 *
 * @author acer
 */
public class DoctorMainFrame extends javax.swing.JFrame {
    PreparedStatement ps = null;
    ResultSet rs = null;
    public String sendName;
    public static int docId;
    /**
     * Creates new form DoctorMainFrame
     */
    public DoctorMainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel_User = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel_Logout = new javax.swing.JLabel();
        jButton_Appointment = new javax.swing.JButton();
        jButton_MyDetails = new javax.swing.JButton();
        jButton_Updateinfo = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Doctor Main Frame");

        jDesktopPane1.setBackground(new java.awt.Color(240, 240, 240));

        jPanel2.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setText("Username:");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(960, 140, 111, 28);

        jLabel_User.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel_User.setText("Doctor");
        jPanel2.add(jLabel_User);
        jLabel_User.setBounds(1080, 140, 150, 28);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel11.setText("Role:");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(960, 170, 60, 28);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel12.setText("Doctor");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(1020, 170, 80, 28);

        jLabel_Logout.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel_Logout.setIcon(new javax.swing.ImageIcon("C:\\Users\\acer\\OneDrive\\Documents\\NetBeansProjects\\Java Project Picture\\LOGOUT (2).png")); // NOI18N
        jLabel_Logout.setText("Logout");
        jLabel_Logout.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel_Logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_Logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_LogoutMouseClicked(evt);
            }
        });
        jPanel2.add(jLabel_Logout);
        jLabel_Logout.setBounds(1110, 50, 80, 30);

        jButton_Appointment.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_Appointment.setIcon(new javax.swing.ImageIcon("C:\\Users\\acer\\OneDrive\\Documents\\NetBeansProjects\\Java Project Picture\\appointmentig.png")); // NOI18N
        jButton_Appointment.setText("Appointments");
        jButton_Appointment.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_Appointment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AppointmentActionPerformed(evt);
            }
        });
        jPanel2.add(jButton_Appointment);
        jButton_Appointment.setBounds(200, 150, 230, 80);

        jButton_MyDetails.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_MyDetails.setIcon(new javax.swing.ImageIcon("C:\\Users\\acer\\OneDrive\\Documents\\NetBeansProjects\\Java Project Picture\\viewuser.png")); // NOI18N
        jButton_MyDetails.setText("My Details");
        jButton_MyDetails.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_MyDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_MyDetailsActionPerformed(evt);
            }
        });
        jPanel2.add(jButton_MyDetails);
        jButton_MyDetails.setBounds(200, 270, 230, 80);

        jButton_Updateinfo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_Updateinfo.setIcon(new javax.swing.ImageIcon("C:\\Users\\acer\\OneDrive\\Documents\\NetBeansProjects\\Java Project Picture\\updateuser (2).png")); // NOI18N
        jButton_Updateinfo.setText("Update Info");
        jButton_Updateinfo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_Updateinfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_UpdateinfoActionPerformed(evt);
            }
        });
        jPanel2.add(jButton_Updateinfo);
        jButton_Updateinfo.setBounds(200, 390, 230, 80);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\acer\\OneDrive\\Documents\\NetBeansProjects\\Java Project Picture\\drportal.jpg")); // NOI18N
        jPanel2.add(jLabel2);
        jLabel2.setBounds(0, 0, 1280, 610);

        jDesktopPane1.setLayer(jPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1280, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 607, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_LogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_LogoutMouseClicked
        // TODO add your handling code here:
        DoctorLoginForm df= new DoctorLoginForm();
        df.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel_LogoutMouseClicked

    private void jButton_AppointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AppointmentActionPerformed
        // TODO add your handling code here:
        Appointment app= new Appointment();
        app.id=docId;
        jDesktopPane1.add(app);
        app.getDMF(this);
        app.setVisible(true);
    }//GEN-LAST:event_jButton_AppointmentActionPerformed

    private void jButton_MyDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_MyDetailsActionPerformed
        // TODO add your handling code here:
//        DoctorDetails dd=new DoctorDetails(docId);
//        jDesktopPane1.add(dd);
//        dd.setVisible(true);
        Connection con = myConnection.getConnection();
        PreparedStatement ps;
        ResultSet rs;
        try {
            String sql="SELECT id,name,address,gender,age,contact,marital,joiningdate,doctortype,username FROM doctor WHERE  id='" + docId + "'";;
            ps = con.prepareStatement(sql);
            rs=ps.executeQuery();
            if(rs.next()){
//                int did;
                DoctorDetails dd=new DoctorDetails();
                jDesktopPane1.add(dd);
                dd.setVisible(true);
                dd.pack();
                //dd.setLocationRelativeTo(null);
                //dd.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                //System.out.println(rs.getInt("id")+" From doctor--login");
                String name=rs.getString("name");
                System.out.println(name);
            dd.jLabel_Id.setText(rs.getString("id"));
            dd.jLabel_dName.setText(name);
            dd.jLabel_Address.setText(rs.getString("address"));
            dd.jLabel_Gender.setText(rs.getString("gender"));
            dd.jLabel_Age.setText(rs.getString("age"));
            dd.jLabel_Contact.setText(rs.getString("contact"));
            dd.jLabel_Marital.setText(rs.getString("marital"));
            dd.jLabel_Jdate.setText(rs.getString("joiningdate"));
            dd.jLabel_Dtype.setText(rs.getString("doctortype"));
            dd.jLabel_Username.setText(rs.getString("username"));
                //this.dispose();
            }
            else{
                JOptionPane.showMessageDialog(null,"Something went wrong");
            }
        }
        catch(Exception ex){
            System.out.println(ex);
        }

    }//GEN-LAST:event_jButton_MyDetailsActionPerformed

    private void jButton_UpdateinfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_UpdateinfoActionPerformed
        // TODO add your handling code here:
        DoctorUpdate du= new DoctorUpdate();
        du.getMB(this);
        du.did=docId;
        jDesktopPane1.add(du);
        du.setVisible(true);
        du.pack();
        
    }//GEN-LAST:event_jButton_UpdateinfoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DoctorMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DoctorMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DoctorMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DoctorMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DoctorMainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Appointment;
    private javax.swing.JButton jButton_MyDetails;
    private javax.swing.JButton jButton_Updateinfo;
    javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel_Logout;
    public javax.swing.JLabel jLabel_User;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
