/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.patientsBA.view;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import org.patientsBA.controller.DoctorFormDAO;
import org.patientsBA.model.DoctorForm;
import org.patientsBA.util.myConnection;

/**
 *
 * @author acer
 */
public class DoctorFormFrame extends javax.swing.JInternalFrame {

    public static int cuid;
    DefaultTableModel model;

    /**
     * Creates new form DoctorFormFrame
     */
    public DoctorFormFrame() {
        initComponents();
        model = new DefaultTableModel(null, new String[]{"Id", "Name", "Address", "Gender", "Age", "Contact", "Marital", "Joiningdate", "Doctortype", "Username", "Password"});
        jTable_Doctor.setModel(model);
        jTextField_Id.setVisible(false);
        jLabel_Id.setVisible(false);
    }

    public void loadData() {
        clearModel();
        DoctorFormDAO dDAO = new DoctorFormDAO();
        ArrayList<DoctorForm> docList = dDAO.fetchData(cuid);
        if(docList==null){
            System.out.println("Hello");
        }
        else{
            //System.out.println("Hii");
            //System.out.println(docList.size());
        for (int i = 0; i < docList.size(); i++) {
                 model.addRow(new Object[]{docList.get(i).getId(),docList.get(i).getName(),docList.get(i).getAddress(),docList.get(i).getGender(),docList.get(i).getAge(),
                 docList.get(i).getContact(),docList.get(i).getMarital(),docList.get(i).getJoiningdate(),docList.get(i).getDoctortype(),docList.get(i).getUsername(),
                 docList.get(i).getPassword()});
        }
        }
    }

    public void clearModel() {
        int count = jTable_Doctor.getRowCount();
        for (int i = 0; i < count; i++) {
            model.removeRow(0);
        }
    }

    public void clear() {
        jTextField_Id.setText("");
        jTextField_Name.setText("");
        jTextField_Address.setText("");
        genderbuttonGroup.clearSelection();
        jTextField_Age.setText("");
        jTextField_Contact.setText("");
        maritalbuttonGroup.clearSelection();
        jDateChooser.setDate(null);
        jTextField_Username.setText("");
        jPasswordField.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genderbuttonGroup = new javax.swing.ButtonGroup();
        maritalbuttonGroup = new javax.swing.ButtonGroup();
        jLabel_Id = new javax.swing.JLabel();
        jTextField_Id = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField_Name = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField_Address = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jRadioButton_Male = new javax.swing.JRadioButton();
        jRadioButton_Female = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jTextField_Age = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField_Contact = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jRadioButton_Married = new javax.swing.JRadioButton();
        jRadioButton_Unmarried = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jDateChooser = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jComboBox_Dtype = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jTextField_Username = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jPasswordField = new javax.swing.JPasswordField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_Doctor = new javax.swing.JTable();
        jTextField_Search = new javax.swing.JTextField();
        jButton_Show = new javax.swing.JButton();
        jButton_Save = new javax.swing.JButton();
        jButton_Update = new javax.swing.JButton();
        jButton_Delete = new javax.swing.JButton();
        jButton_Clear = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Doctor Form");
        setPreferredSize(new java.awt.Dimension(1200, 647));

        jLabel_Id.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_Id.setText("Id");

        jTextField_Id.setEditable(false);
        jTextField_Id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_IdActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Name");

        jTextField_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_NameActionPerformed(evt);
            }
        });
        jTextField_Name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_NameKeyTyped(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Address");

        jTextField_Address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_AddressActionPerformed(evt);
            }
        });
        jTextField_Address.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_AddressKeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Gender");

        genderbuttonGroup.add(jRadioButton_Male);
        jRadioButton_Male.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jRadioButton_Male.setText("Male");
        jRadioButton_Male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_MaleActionPerformed(evt);
            }
        });

        genderbuttonGroup.add(jRadioButton_Female);
        jRadioButton_Female.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jRadioButton_Female.setText("Female");
        jRadioButton_Female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_FemaleActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Age");

        jTextField_Age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_AgeActionPerformed(evt);
            }
        });
        jTextField_Age.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_AgeKeyPressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Contact");

        jTextField_Contact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_ContactActionPerformed(evt);
            }
        });
        jTextField_Contact.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_ContactKeyPressed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Marital Status");

        maritalbuttonGroup.add(jRadioButton_Married);
        jRadioButton_Married.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jRadioButton_Married.setText("Married");
        jRadioButton_Married.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_MarriedActionPerformed(evt);
            }
        });

        maritalbuttonGroup.add(jRadioButton_Unmarried);
        jRadioButton_Unmarried.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jRadioButton_Unmarried.setText("Unmarried");
        jRadioButton_Unmarried.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_UnmarriedActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Joining Date");

        jDateChooser.setDateFormatString("yyyy-MM-d");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Doctor Type");

        jComboBox_Dtype.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jComboBox_Dtype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "General Physician", "Gynecologist", "Surgeon", "Cardiologist", "Nephrologist", "Neurologist" }));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Username");

        jTextField_Username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_UsernameActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Password");

        jPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldActionPerformed(evt);
            }
        });

        jTable_Doctor.setBorder(new javax.swing.border.MatteBorder(null));
        jTable_Doctor.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTable_Doctor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable_Doctor.setGridColor(new java.awt.Color(0, 0, 0));
        jTable_Doctor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_DoctorMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable_Doctor);

        jTextField_Search.setBorder(null);
        jTextField_Search.setPreferredSize(new java.awt.Dimension(6, 22));
        jTextField_Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_SearchActionPerformed(evt);
            }
        });
        jTextField_Search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_SearchKeyReleased(evt);
            }
        });

        jButton_Show.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton_Show.setText("Show");
        jButton_Show.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_Show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ShowActionPerformed(evt);
            }
        });

        jButton_Save.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton_Save.setIcon(new javax.swing.ImageIcon("C:\\Users\\acer\\OneDrive\\Documents\\NetBeansProjects\\Java Project Picture\\adduser.png")); // NOI18N
        jButton_Save.setText("Save");
        jButton_Save.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SaveActionPerformed(evt);
            }
        });

        jButton_Update.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton_Update.setIcon(new javax.swing.ImageIcon("C:\\Users\\acer\\OneDrive\\Documents\\NetBeansProjects\\Java Project Picture\\UPDATESMALL.png")); // NOI18N
        jButton_Update.setText("Update");
        jButton_Update.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_UpdateActionPerformed(evt);
            }
        });

        jButton_Delete.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton_Delete.setIcon(new javax.swing.ImageIcon("C:\\Users\\acer\\OneDrive\\Documents\\NetBeansProjects\\Java Project Picture\\DELETESMALL.png")); // NOI18N
        jButton_Delete.setText("Delete");
        jButton_Delete.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DeleteActionPerformed(evt);
            }
        });

        jButton_Clear.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton_Clear.setText("Clear");
        jButton_Clear.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ClearActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Search");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_Id)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7)
                    .addComponent(jLabel1)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jTextField_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel12)
                                .addGap(60, 60, 60))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_Id, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jComboBox_Dtype, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jDateChooser, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jTextField_Age, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_Contact, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_Address, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jRadioButton_Male)
                                        .addGap(18, 18, 18)
                                        .addComponent(jRadioButton_Female))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jRadioButton_Married)
                                        .addGap(18, 18, 18)
                                        .addComponent(jRadioButton_Unmarried)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jTextField_Username))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(434, 434, 434)
                                .addComponent(jButton_Show, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(407, 407, 407)
                                .addComponent(jLabel13))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(265, 265, 265)
                                .addComponent(jLabel14)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 718, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(42, 42, 42))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jButton_Save, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jButton_Update, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jButton_Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jButton_Clear, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField_Id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Id))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_Name)
                            .addComponent(jTextField_Search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextField_Address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jRadioButton_Male, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jRadioButton_Female, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_Age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_Contact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButton_Married)
                            .addComponent(jRadioButton_Unmarried))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jComboBox_Dtype, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_Username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_Save)
                            .addComponent(jButton_Update)
                            .addComponent(jButton_Delete)
                            .addComponent(jButton_Clear, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(46, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_Show, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_IdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_IdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_IdActionPerformed

    private void jTextField_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_NameActionPerformed

    private void jTextField_AddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_AddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_AddressActionPerformed

    private void jRadioButton_MaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_MaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton_MaleActionPerformed

    private void jRadioButton_FemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_FemaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton_FemaleActionPerformed

    private void jTextField_AgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_AgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_AgeActionPerformed

    private void jTextField_AgeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_AgeKeyPressed
        // TODO add your handling code here:
        String age = jTextField_Age.getText();
        int length = age.length();
        char c = evt.getKeyChar();
        //check for number 0 to 9
        if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9') {
            //check for length not more than 2 digit
            if (length < 2) {
                jTextField_Age.setEditable(true);
            } else {
                jTextField_Age.setEditable(false);
            }
        } else {
            //not allows key backsapce and delete for edit
            if (evt.getExtendedKeyCode() == KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode() == KeyEvent.VK_DELETE) {
                jTextField_Age.setEditable(true);
            } else {
                jTextField_Age.setEditable(false);
            }
        }
    }//GEN-LAST:event_jTextField_AgeKeyPressed

    private void jTextField_ContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_ContactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_ContactActionPerformed

    private void jTextField_ContactKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_ContactKeyPressed
        // TODO add your handling code here:
        String contact = jTextField_Contact.getText();
        int length = contact.length();
        char c = evt.getKeyChar();
        //check for number 0 to 9
        if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9') {
            //check for length not more than 10 digit
            if (length < 10) {
                jTextField_Contact.setEditable(true);
            } else {
                jTextField_Contact.setEditable(false);
            }
        } else {
            //not allows key backsapce and delete for edit
            if (evt.getExtendedKeyCode() == KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode() == KeyEvent.VK_DELETE) {
                jTextField_Contact.setEditable(true);
            } else {
                jTextField_Contact.setEditable(false);
            }
        }
    }//GEN-LAST:event_jTextField_ContactKeyPressed

    private void jRadioButton_MarriedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_MarriedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton_MarriedActionPerformed

    private void jRadioButton_UnmarriedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_UnmarriedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton_UnmarriedActionPerformed

    private void jTextField_UsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_UsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_UsernameActionPerformed

    private void jPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldActionPerformed

    private void jTable_DoctorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_DoctorMouseClicked
        // TODO add your handling code here:
        int row = jTable_Doctor.getSelectedRow();
        jTextField_Id.setText(jTable_Doctor.getValueAt(row, 0).toString());
        jTextField_Name.setText(jTable_Doctor.getValueAt(row, 1).toString());
        jTextField_Address.setText(jTable_Doctor.getValueAt(row, 2).toString());
        String gender = jTable_Doctor.getValueAt(row, 3).toString();
        if (gender.equals("Male")) {
            jRadioButton_Male.setSelected(true);
        } else {
            jRadioButton_Female.setSelected(true);
        }
        jTextField_Age.setText(jTable_Doctor.getValueAt(row, 4).toString());
        jTextField_Contact.setText(jTable_Doctor.getValueAt(row, 5).toString());
        String marital = jTable_Doctor.getValueAt(row, 6).toString();
        if (marital.equals("Married")) {
            jRadioButton_Married.setSelected(true);
        } else {
            jRadioButton_Unmarried.setSelected(true);
        }
        try {
            //int srow = jTable_Doctor.getSelectedRow();
            Date date = new SimpleDateFormat("yyyy-MM-dd").parse((String) jTable_Doctor.getValueAt(row, 7));
            jDateChooser.setDate(date);
        } catch (Exception e) {
            System.out.println(e);
        }
        jComboBox_Dtype.setSelectedItem(jTable_Doctor.getValueAt(row, 8).toString());
        jTextField_Username.setText(jTable_Doctor.getValueAt(row, 9).toString());
        jPasswordField.setText(jTable_Doctor.getValueAt(row, 10).toString());
    }//GEN-LAST:event_jTable_DoctorMouseClicked

    private void jTextField_SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_SearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_SearchActionPerformed

    private void jTextField_SearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_SearchKeyReleased
        // TODO add your handling code here:
        DefaultTableModel table = (DefaultTableModel) jTable_Doctor.getModel();
        String search = jTextField_Search.getText();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(table);
        jTable_Doctor.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(search));
    }//GEN-LAST:event_jTextField_SearchKeyReleased

    private void jButton_ShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ShowActionPerformed
        // TODO add your handling code here:
        loadData();
    }//GEN-LAST:event_jButton_ShowActionPerformed

    private void jButton_SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SaveActionPerformed
        // TODO add your handling code here:
        if(jTextField_Id.getText().equals("")==false){
            JOptionPane.showMessageDialog(null,"Please clear all fields first");
            return;
        }
        String name = jTextField_Name.getText().trim();
        String address = jTextField_Address.getText().trim();
//        jRadioButton_Male.setActionCommand("Male");
//        jRadioButton_Female.setActionCommand("Female");
//        String gender = genderbuttonGroup.getSelection().getActionCommand();
        String gender="";
        if(jRadioButton_Male.isSelected()){
             gender="Male";
        }
        else if(jRadioButton_Female.isSelected()){
             gender="Female";
        }
        String age = jTextField_Age.getText().trim();
        String contact = jTextField_Contact.getText().trim();
//        jRadioButton_Married.setActionCommand("Married");
//        jRadioButton_Unmarried.setActionCommand("Unmarried");
//        String marital = maritalbuttonGroup.getSelection().getActionCommand();
        String marital="";
        if(jRadioButton_Married.isSelected()){
             marital="Married";
        }
        else if(jRadioButton_Unmarried.isSelected()){
             marital="Unmarried";
        }
        String jdate = ((JTextField) jDateChooser.getDateEditor().getUiComponent()).getText().trim();
        System.out.println(jdate);
        Date currentDate=new Date();
        //System.out.println(currentDate);
        SimpleDateFormat dateFormat=new SimpleDateFormat("yyyy-MM-dd");
        String date = dateFormat.format(currentDate);
        System.out.println(date);
        String dtype = jComboBox_Dtype.getSelectedItem().toString().trim();
        String username = jTextField_Username.getText().trim();
        String password = String.valueOf(jPasswordField.getPassword()).trim();
        
        try{
            boolean flag = false;
            Set <String> pNumber = new HashSet <String>();
            Connection con=myConnection.getConnection();
            PreparedStatement ps = null;
            ResultSet rs = null;
            String queryTwo = "select contact from doctor";
            ps = con.prepareStatement(queryTwo);
            rs = ps.executeQuery();
            while (rs.next()) {
                pNumber.add(rs.getString("contact"));
                //System.out.println(rs.getString(1));
            }
            //System.out.println(pNumber.size());
            for (int i = 0; i < pNumber.size(); i++) {
                if (pNumber.contains(contact)) {
                    JOptionPane.showMessageDialog(null,"Contact is already registered");
                    //System.out.println("Already number registered");
                    //pNumber.remove(phoneNumber);
                    //System.out.println(pNumber);
                    flag = true;
                    return;
                }
            }
              if (pNumber.equals(contact)) {
                JOptionPane.showMessageDialog(null,"Contact is already registered");
                //System.out.println("Already number registered");
                return;
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Contact is already registered");
            try {
                throw e;
            } catch (Exception ex) {
                Logger.getLogger(DoctorFormFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        if(name.equals("") || address.equals("") || gender.equals("") || age.equals("") || contact.equals("") || marital.equals("") || jdate.equals("")
                || dtype.equals("") || username.equals("") || password.equals("")){
      
        JOptionPane.showMessageDialog(null,"One or more fields are empty");
        }
        
        else if(!Pattern.matches("[9]{1}+[8]{1}+[0-9]+$",contact)){
            JOptionPane.showMessageDialog(null,"Number must start with 98");
        }
        
        else if((jdate.compareTo(date)<0)){
            
            JOptionPane.showMessageDialog(null,"Date is old");
        }    
        
        else if((date.compareTo(date)>1)){
            JOptionPane.showMessageDialog(null,"Date is new");
        }
        
        else{
        //set these value into model class "DoctorFormFrame" object
        DoctorForm ob = new DoctorForm();
        ob.setName(name);
        ob.setAddress(address);
        ob.setGender(gender);
        ob.setAge(age);
        ob.setContact(contact);
        ob.setMarital(marital);
        ob.setJoiningdate(jdate);
        ob.setDoctortype(dtype);
        ob.setUsername(username);
        ob.setPassword(password);
        ob.setAdminid(cuid);
        //Hand over this model object to controller class
        DoctorFormDAO dDAO = new DoctorFormDAO();
        dDAO.saveData(ob);
        loadData();
        clear();
        }
    }//GEN-LAST:event_jButton_SaveActionPerformed

    private void jButton_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_UpdateActionPerformed
        // TODO add your handling code here:
        if(jTextField_Id.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Please select one record for update");
            return;
        }
        int id = Integer.parseInt(jTextField_Id.getText());
        String name = jTextField_Name.getText();
        String address = jTextField_Address.getText();
        jRadioButton_Male.setActionCommand("Male");
        jRadioButton_Female.setActionCommand("Female");
        String gender = genderbuttonGroup.getSelection().getActionCommand();
        String age = jTextField_Age.getText();
        String contact = jTextField_Contact.getText();
        jRadioButton_Married.setActionCommand("Married");
        jRadioButton_Unmarried.setActionCommand("Unmarried");
        String marital = maritalbuttonGroup.getSelection().getActionCommand();
        String jdate = ((JTextField) jDateChooser.getDateEditor().getUiComponent()).getText();
        String dtype = jComboBox_Dtype.getSelectedItem().toString();
        String username = jTextField_Username.getText();
        String password = String.valueOf(jPasswordField.getPassword());

        DoctorForm ob = new DoctorForm();
        ob.setId(id);
        ob.setName(name);
        ob.setAddress(address);
        ob.setGender(gender);
        ob.setAge(age);
        ob.setContact(contact);
        ob.setMarital(marital);
        ob.setJoiningdate(jdate);
        ob.setDoctortype(dtype);
        ob.setUsername(username);
        ob.setPassword(password);
        ob.setAdminid(cuid);

        DoctorFormDAO dDAO = new DoctorFormDAO();
        dDAO.updateRecord(ob);
        loadData();
        clear();
    }//GEN-LAST:event_jButton_UpdateActionPerformed

    private void jButton_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DeleteActionPerformed
        // TODO add your handling code here:
        if(jTextField_Id.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Please select one record for delete");
            return;
        }
        int id = Integer.parseInt(jTextField_Id.getText());
        DoctorForm ob = new DoctorForm();
        ob.setId(id);
        DoctorFormDAO dDAO = new DoctorFormDAO();
        dDAO.deleteRecord(ob);
        loadData();
        clear();
    }//GEN-LAST:event_jButton_DeleteActionPerformed

    private void jButton_ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ClearActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_jButton_ClearActionPerformed

    private void jTextField_NameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_NameKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(!(Character.isAlphabetic(c)) || (c==KeyEvent.VK_PERIOD) || (c==KeyEvent.VK_BACK_SPACE)){
            evt.consume();
        }
    }//GEN-LAST:event_jTextField_NameKeyTyped

    private void jTextField_AddressKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_AddressKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(!(Character.isAlphabetic(c) || (c==KeyEvent.VK_PERIOD) || (c==KeyEvent.VK_BACK_SPACE) || Character.isDigit(c))){
            evt.consume();
        }
    }//GEN-LAST:event_jTextField_AddressKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup genderbuttonGroup;
    private javax.swing.JButton jButton_Clear;
    private javax.swing.JButton jButton_Delete;
    private javax.swing.JButton jButton_Save;
    private javax.swing.JButton jButton_Show;
    private javax.swing.JButton jButton_Update;
    private javax.swing.JComboBox<String> jComboBox_Dtype;
    private com.toedter.calendar.JDateChooser jDateChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_Id;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JRadioButton jRadioButton_Female;
    private javax.swing.JRadioButton jRadioButton_Male;
    private javax.swing.JRadioButton jRadioButton_Married;
    private javax.swing.JRadioButton jRadioButton_Unmarried;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable_Doctor;
    private javax.swing.JTextField jTextField_Address;
    private javax.swing.JTextField jTextField_Age;
    private javax.swing.JTextField jTextField_Contact;
    private javax.swing.JTextField jTextField_Id;
    private javax.swing.JTextField jTextField_Name;
    private javax.swing.JTextField jTextField_Search;
    private javax.swing.JTextField jTextField_Username;
    private javax.swing.ButtonGroup maritalbuttonGroup;
    // End of variables declaration//GEN-END:variables
}
