/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.patientsBA.view;

import java.awt.event.KeyEvent;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import org.patientsBA.controller.ReceptionistFormDAO;
import org.patientsBA.model.ReceptionistForm;
import RKinfotech.MysqlMd5;
import java.util.logging.Level;
import java.util.logging.Logger;


/**
 *
 * @author acer
 */
public class ReceptionistFormFrame extends javax.swing.JInternalFrame {

    public static int currentUserId;
    DefaultTableModel model;

    /**
     * Creates new form
     */
    public ReceptionistFormFrame() {
        initComponents();
        model = new DefaultTableModel(null, new String[]{"Id", "Name", "Address", "Gender", "Age", "Contact", "Maital", "Joiningdate", "Username", "Password"});
        jTable_Recep.setModel(model);
    }

    public void loadData() {
        clearModel();
        ReceptionistFormDAO rDAO = new ReceptionistFormDAO();
        ArrayList<ReceptionistForm> recepList = rDAO.fetchData(currentUserId);
        for (int i = 0; i < recepList.size(); i++) {
            model.addRow(new Object[]{recepList.get(i).getId(), recepList.get(i).getName(), recepList.get(i).getAddress(), recepList.get(i).getGender(), recepList.get(i).getAge(),
                 recepList.get(i).getContact(), recepList.get(i).getMarital(), recepList.get(i).getJoiningdate(), recepList.get(i).getUsername(), recepList.get(i).getPassword()});
        }
    }

    public void clearModel() {
        int count = model.getRowCount();
        for (int i = 0; i < count; i++) {
            model.removeRow(0);
        }
    }

    public void clear() {
        jTextField_Id.setText("");
        jTextField_Name.setText("");
        jTextField_Address.setText("");
        //jTextField_Address.setText("");gender
        genderbuttonGroup.clearSelection();
        jTextField_Age.setText("");
        jTextField_Contact.setText("");
        maritalbuttonGroup.clearSelection();
        jDateChooser.setDate(null);
        jTextField_Username.setText("");
        jPasswordField.setText("");
    }

//    public boolean vData(){
//        if(jTextField_Name.getText().equals("") || jTextField_Address.getText().equals("") || jTextField_Age.getText().equals("")
//                || jTextField_Contact.getText().equals("") ||jTextField_Username.getText().equals("") || jPasswordField.getText().equals("")){
//            JOptionPane.showMessageDialog(null,"One or more fields are empty");
//        return false;
//        }
//          else{
//        return true;
//    }
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genderbuttonGroup = new javax.swing.ButtonGroup();
        maritalbuttonGroup = new javax.swing.ButtonGroup();
        jLabel3 = new javax.swing.JLabel();
        jTextField_Id = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField_Name = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField_Address = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jRadioButton_Male = new javax.swing.JRadioButton();
        jRadioButton_Female = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jTextField_Age = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField_Contact = new javax.swing.JTextField();
        jButton_Save = new javax.swing.JButton();
        jButton_Update = new javax.swing.JButton();
        jButton_Delete = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField_Username = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_Recep = new javax.swing.JTable();
        jButton_Show = new javax.swing.JButton();
        jRadioButton_Married = new javax.swing.JRadioButton();
        jRadioButton_Unmarried = new javax.swing.JRadioButton();
        jDateChooser = new com.toedter.calendar.JDateChooser();
        jPasswordField = new javax.swing.JPasswordField();
        jTextField_Search = new javax.swing.JTextField();
        jButton_Clear = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Receptionist Form");
        setMinimumSize(new java.awt.Dimension(1232, 542));
        setPreferredSize(new java.awt.Dimension(1235, 607));

        jLabel3.setText("Id");

        jTextField_Id.setEditable(false);
        jTextField_Id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_IdActionPerformed(evt);
            }
        });

        jLabel2.setText("Name");

        jTextField_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_NameActionPerformed(evt);
            }
        });

        jLabel7.setText("Address");

        jTextField_Address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_AddressActionPerformed(evt);
            }
        });

        jLabel1.setText("Gender");

        genderbuttonGroup.add(jRadioButton_Male);
        jRadioButton_Male.setText("Male");
        jRadioButton_Male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_MaleActionPerformed(evt);
            }
        });

        genderbuttonGroup.add(jRadioButton_Female);
        jRadioButton_Female.setText("Female");
        jRadioButton_Female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_FemaleActionPerformed(evt);
            }
        });

        jLabel8.setText("Age");

        jTextField_Age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_AgeActionPerformed(evt);
            }
        });
        jTextField_Age.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_AgeKeyPressed(evt);
            }
        });

        jLabel5.setText("Contact");

        jTextField_Contact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_ContactActionPerformed(evt);
            }
        });
        jTextField_Contact.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_ContactKeyPressed(evt);
            }
        });

        jButton_Save.setIcon(new javax.swing.ImageIcon("C:\\Users\\acer\\OneDrive\\Documents\\NetBeansProjects\\Java Project Picture\\adduser.png")); // NOI18N
        jButton_Save.setText("Save");
        jButton_Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SaveActionPerformed(evt);
            }
        });

        jButton_Update.setIcon(new javax.swing.ImageIcon("C:\\Users\\acer\\OneDrive\\Documents\\NetBeansProjects\\Java Project Picture\\UPDATESMALL.png")); // NOI18N
        jButton_Update.setText("Update");
        jButton_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_UpdateActionPerformed(evt);
            }
        });

        jButton_Delete.setIcon(new javax.swing.ImageIcon("C:\\Users\\acer\\OneDrive\\Documents\\NetBeansProjects\\Java Project Picture\\DELETESMALL.png")); // NOI18N
        jButton_Delete.setText("Delete");
        jButton_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DeleteActionPerformed(evt);
            }
        });

        jLabel4.setText("Username");

        jTextField_Username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_UsernameActionPerformed(evt);
            }
        });

        jLabel6.setText("Password");

        jLabel9.setText("Joining Date");

        jLabel10.setText("Marital Status");

        jTable_Recep.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTable_Recep.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTable_Recep.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable_Recep.setGridColor(new java.awt.Color(0, 0, 0));
        jTable_Recep.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_RecepMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable_Recep);

        jButton_Show.setText("Show");
        jButton_Show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ShowActionPerformed(evt);
            }
        });

        maritalbuttonGroup.add(jRadioButton_Married);
        jRadioButton_Married.setText("Married");
        jRadioButton_Married.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_MarriedActionPerformed(evt);
            }
        });

        maritalbuttonGroup.add(jRadioButton_Unmarried);
        jRadioButton_Unmarried.setText("Unmarried");
        jRadioButton_Unmarried.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_UnmarriedActionPerformed(evt);
            }
        });

        jDateChooser.setDateFormatString("yyyy-MM-d");

        jPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldActionPerformed(evt);
            }
        });

        jTextField_Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_SearchActionPerformed(evt);
            }
        });
        jTextField_Search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_SearchKeyReleased(evt);
            }
        });

        jButton_Clear.setText("Clear");
        jButton_Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel1)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addComponent(jLabel3)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_Id, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_Address, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jRadioButton_Male)
                                        .addGap(31, 31, 31)
                                        .addComponent(jRadioButton_Female))
                                    .addComponent(jTextField_Age, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_Contact, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jRadioButton_Married)
                                        .addGap(18, 18, 18)
                                        .addComponent(jRadioButton_Unmarried))
                                    .addComponent(jTextField_Username, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(88, 88, 88)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 767, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jButton_Show)
                                                .addGap(333, 333, 333))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jTextField_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(280, 280, 280))))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton_Save)
                                .addGap(33, 33, 33)
                                .addComponent(jButton_Update)
                                .addGap(32, 32, 32)
                                .addComponent(jButton_Delete)
                                .addGap(31, 31, 31)
                                .addComponent(jButton_Clear, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextField_Id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField_Search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField_Address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jRadioButton_Male, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRadioButton_Female, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jTextField_Age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField_Contact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jRadioButton_Married)
                                    .addComponent(jRadioButton_Unmarried)))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton_Show, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_Username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Save)
                    .addComponent(jButton_Update)
                    .addComponent(jButton_Delete)
                    .addComponent(jButton_Clear, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(89, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_IdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_IdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_IdActionPerformed

    private void jTextField_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_NameActionPerformed

    private void jTextField_AddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_AddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_AddressActionPerformed

    private void jTextField_ContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_ContactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_ContactActionPerformed


    private void jButton_SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SaveActionPerformed
        // TODO add your handling code here:
        if(jTextField_Id.getText().equals("")==false){
            JOptionPane.showMessageDialog(null,"Please clear all fields first");
            return;
        }
        String name = jTextField_Name.getText().trim();
        String address = jTextField_Address.getText().trim();
//        jRadioButton_Male.setActionCommand("Male");
//        jRadioButton_Female.setActionCommand("Female");
        //String gender = genderbuttonGroup.getSelection().getActionCommand();
        String gender="";
        if(jRadioButton_Male.isSelected()){
             gender="Male";
        }
        else if(jRadioButton_Female.isSelected()){
             gender="Female";
        }
        String age = jTextField_Age.getText().trim();
        String contact = jTextField_Contact.getText().trim();
//        jRadioButton_Married.setActionCommand("Married");
//        jRadioButton_Unmarried.setActionCommand("Unmarried");
//        String marital = maritalbuttonGroup.getSelection().getActionCommand();
        String marital="";
        if(jRadioButton_Married.isSelected()){
             marital="Married";
        }
        else if(jRadioButton_Unmarried.isSelected()){
             marital="Unmarried";
        }
        String jdate = ((JTextField) jDateChooser.getDateEditor().getUiComponent()).getText().trim();
        String username = jTextField_Username.getText().trim();
        String pswd = String.valueOf(jPasswordField.getPassword()).trim();
        String password = "";
        try {
            password = MysqlMd5.getRKmd5(pswd);
        } catch (NoSuchAlgorithmException ex) {
            Logger.getLogger(ReceptionistFormFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        if(name.equals("") || address.equals("") || gender.equals("") || age.equals("") || contact.equals("") || marital.equals("") || jdate.equals("")
                || username.equals("") || password.equals("")){
      
        JOptionPane.showMessageDialog(null,"One or more fields are empty");
        }
        else{
        //set these value into model class "ReceptionistFormFrame" object
        ReceptionistForm ob = new ReceptionistForm();
        ob.setName(name);
        ob.setAddress(address);
        ob.setGender(gender);
        ob.setAge(age);
        ob.setContact(contact);
        ob.setMarital(marital);
        ob.setJoiningdate(jdate);
        ob.setUsername(username);
        ob.setPassword(password);
        ob.setAdminid(currentUserId);
        //Hand over this model object to controller class
        ReceptionistFormDAO rDAO = new ReceptionistFormDAO();
        rDAO.saveData(ob);
        loadData();
        clear();
        }
    }//GEN-LAST:event_jButton_SaveActionPerformed

    private void jButton_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_UpdateActionPerformed
        // TODO add your handling code here:
        if(jTextField_Id.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Please select one record for update");
            return;
        }
        int id = Integer.parseInt(jTextField_Id.getText());
        String name = jTextField_Name.getText();
        String address = jTextField_Address.getText();
        jRadioButton_Male.setActionCommand("Male");
        jRadioButton_Female.setActionCommand("Female");
        String gender = genderbuttonGroup.getSelection().getActionCommand();
        String age = jTextField_Age.getText();
        String contact = jTextField_Contact.getText();
        jRadioButton_Married.setActionCommand("Married");
        jRadioButton_Unmarried.setActionCommand("Unmarried");
        String marital = maritalbuttonGroup.getSelection().getActionCommand();
        String jdate = ((JTextField) jDateChooser.getDateEditor().getUiComponent()).getText();
        String username = jTextField_Username.getText();
        String password = String.valueOf(jPasswordField.getPassword());

        ReceptionistForm ob = new ReceptionistForm();
        ob.setId(id);
        ob.setName(name);
        ob.setAddress(address);
        ob.setGender(gender);
        ob.setAge(age);
        ob.setContact(contact);
        ob.setMarital(marital);
        ob.setJoiningdate(jdate);
        ob.setUsername(username);
        ob.setPassword(password);
        ob.setAdminid(currentUserId);

        ReceptionistFormDAO rDAO = new ReceptionistFormDAO();
        rDAO.updateRecord(ob);
        loadData();
        clear();
    }//GEN-LAST:event_jButton_UpdateActionPerformed

    private void jButton_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DeleteActionPerformed
        // TODO add your handling code here:
        if(jTextField_Id.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Please select one record for delete");
            return;
        }
        int id = Integer.parseInt(jTextField_Id.getText());
        ReceptionistForm ob = new ReceptionistForm();
        ob.setId(id);
        ReceptionistFormDAO rDAO = new ReceptionistFormDAO();
        rDAO.deleteRecord(ob);
        loadData();
        clear();
    }//GEN-LAST:event_jButton_DeleteActionPerformed

    private void jTextField_UsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_UsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_UsernameActionPerformed


    private void jTable_RecepMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_RecepMouseClicked
        // TODO add your handling code here:
        int row = jTable_Recep.getSelectedRow();
        jTextField_Id.setText(jTable_Recep.getValueAt(row, 0).toString());
        jTextField_Name.setText(jTable_Recep.getValueAt(row, 1).toString());
        jTextField_Address.setText(jTable_Recep.getValueAt(row, 2).toString());
        String gender = jTable_Recep.getValueAt(row, 3).toString();
        if (gender.equals("Male")) {
            jRadioButton_Male.setSelected(true);
        } else {
            jRadioButton_Female.setSelected(true);
        }
        jTextField_Age.setText(jTable_Recep.getValueAt(row, 4).toString());
        jTextField_Contact.setText(jTable_Recep.getValueAt(row, 5).toString());
        String marital = jTable_Recep.getValueAt(row, 6).toString();
        if (marital.equals("Married")) {
            jRadioButton_Married.setSelected(true);
        } else {
            jRadioButton_Unmarried.setSelected(true);
        }
        try {
            int srow = jTable_Recep.getSelectedRow();
            Date date = new SimpleDateFormat("yyyy-MM-dd").parse((String) jTable_Recep.getValueAt(row, 7));
            jDateChooser.setDate(date);
        } catch (Exception e) {
            System.out.println(e);
        }
        jTextField_Username.setText(jTable_Recep.getValueAt(row, 8).toString());
        jPasswordField.setText(jTable_Recep.getValueAt(row, 9).toString());
    }//GEN-LAST:event_jTable_RecepMouseClicked

    private void jButton_ShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ShowActionPerformed
        // TODO add your handling code here:
        loadData();
    }//GEN-LAST:event_jButton_ShowActionPerformed

    private void jRadioButton_MaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_MaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton_MaleActionPerformed

    private void jRadioButton_FemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_FemaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton_FemaleActionPerformed

    private void jRadioButton_UnmarriedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_UnmarriedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton_UnmarriedActionPerformed

    private void jTextField_AgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_AgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_AgeActionPerformed

    private void jRadioButton_MarriedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_MarriedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton_MarriedActionPerformed

    private void jPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldActionPerformed

    private void jTextField_SearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_SearchKeyReleased
        // TODO add your handling code here:
        DefaultTableModel table = (DefaultTableModel) jTable_Recep.getModel();
        String search = jTextField_Search.getText();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(table);
        jTable_Recep.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(search));
    }//GEN-LAST:event_jTextField_SearchKeyReleased

    private void jTextField_SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_SearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_SearchActionPerformed

    private void jTextField_ContactKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_ContactKeyPressed
        // TODO add your handling code here:
        String contact = jTextField_Contact.getText();
        int length = contact.length();
        char c = evt.getKeyChar();
        //check for number 0 to 9
        if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9') {
            //check for length not more than 10 digit
            if (length < 10) {
                jTextField_Contact.setEditable(true);
                //JOptionPane.showMessageDialog(null,"Enter full phone number");
            } else {
                jTextField_Contact.setEditable(false);
            }
        } else {
            //not allows key backsapce and delete for edit
            if (evt.getExtendedKeyCode() == KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode() == KeyEvent.VK_DELETE) {
                jTextField_Contact.setEditable(true);
            } else {
                jTextField_Contact.setEditable(false);
            }
        }
    }//GEN-LAST:event_jTextField_ContactKeyPressed

    private void jTextField_AgeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_AgeKeyPressed
        // TODO add your handling code here:
        String age = jTextField_Age.getText();
        int length = age.length();
        char c = evt.getKeyChar();
        //check for number 0 to 9
        if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9') {
            //check for length not more than 2 digit
            if (length < 2) {
                jTextField_Age.setEditable(true);
            } else {
                jTextField_Age.setEditable(false);
            }
        } else {
            //not allows key backsapce and delete for edit
            if (evt.getExtendedKeyCode() == KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode() == KeyEvent.VK_DELETE) {
                jTextField_Age.setEditable(true);
            } else {
                jTextField_Age.setEditable(false);
            }
        }
    }//GEN-LAST:event_jTextField_AgeKeyPressed

    private void jButton_ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ClearActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_jButton_ClearActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup genderbuttonGroup;
    private javax.swing.JButton jButton_Clear;
    private javax.swing.JButton jButton_Delete;
    private javax.swing.JButton jButton_Save;
    private javax.swing.JButton jButton_Show;
    private javax.swing.JButton jButton_Update;
    private com.toedter.calendar.JDateChooser jDateChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JRadioButton jRadioButton_Female;
    private javax.swing.JRadioButton jRadioButton_Male;
    private javax.swing.JRadioButton jRadioButton_Married;
    private javax.swing.JRadioButton jRadioButton_Unmarried;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable_Recep;
    private javax.swing.JTextField jTextField_Address;
    private javax.swing.JTextField jTextField_Age;
    private javax.swing.JTextField jTextField_Contact;
    private javax.swing.JTextField jTextField_Id;
    private javax.swing.JTextField jTextField_Name;
    private javax.swing.JTextField jTextField_Search;
    private javax.swing.JTextField jTextField_Username;
    private javax.swing.ButtonGroup maritalbuttonGroup;
    // End of variables declaration//GEN-END:variables

    void setLocationRelativeTo(Object object) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void setAddress(String address) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void setAge(String age) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void setContact(String contact) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void setJdate(String jdate) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void setUsername(String username) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void setPassword(String password) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void setGender(String gender) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void setMarital(String marital) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
