/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.patientsBA.view;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import org.patientsBA.util.myConnection;

/**
 *
 * @author Raj Cassette
 */
public class ReceptionistMainFrame extends javax.swing.JFrame {
    
    PreparedStatement ps = null;
    ResultSet rs = null;
    public static int repId;
    /**
     * Creates new form ReceptionistMainFrame
     */
    public ReceptionistMainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel_Logout = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel_User = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton_Appointment = new javax.swing.JButton();
        jButton_MyDetails = new javax.swing.JButton();
        jButton_Updateinfo = new javax.swing.JButton();
        jButton_Patient = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Receptionist Main Frame");

        jDesktopPane1.setBackground(new java.awt.Color(240, 240, 240));

        jPanel1.setLayout(null);

        jLabel_Logout.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel_Logout.setIcon(new javax.swing.ImageIcon("C:\\Users\\acer\\OneDrive\\Documents\\NetBeansProjects\\Java Project Picture\\LOGOUT (2).png")); // NOI18N
        jLabel_Logout.setText("Logout");
        jLabel_Logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_Logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_LogoutMouseClicked(evt);
            }
        });
        jPanel1.add(jLabel_Logout);
        jLabel_Logout.setBounds(1060, 40, 80, 30);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setText("Username:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(890, 100, 111, 28);

        jLabel_User.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel_User.setText("Receptionist");
        jPanel1.add(jLabel_User);
        jLabel_User.setBounds(1010, 100, 160, 28);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel11.setText("Role:");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(890, 130, 60, 28);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel12.setText("Receptionist");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(960, 130, 130, 28);

        jButton_Appointment.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_Appointment.setIcon(new javax.swing.ImageIcon("C:\\Users\\acer\\OneDrive\\Documents\\NetBeansProjects\\Java Project Picture\\appointmentig.png")); // NOI18N
        jButton_Appointment.setText("Set Appointments");
        jButton_Appointment.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_Appointment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AppointmentActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Appointment);
        jButton_Appointment.setBounds(200, 110, 220, 80);

        jButton_MyDetails.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_MyDetails.setIcon(new javax.swing.ImageIcon("C:\\Users\\acer\\OneDrive\\Documents\\NetBeansProjects\\Java Project Picture\\viewuser.png")); // NOI18N
        jButton_MyDetails.setText("  My Details");
        jButton_MyDetails.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_MyDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_MyDetailsActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_MyDetails);
        jButton_MyDetails.setBounds(200, 470, 220, 80);

        jButton_Updateinfo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_Updateinfo.setIcon(new javax.swing.ImageIcon("C:\\Users\\acer\\OneDrive\\Documents\\NetBeansProjects\\Java Project Picture\\updateuser (2).png")); // NOI18N
        jButton_Updateinfo.setText("  Update Info");
        jButton_Updateinfo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_Updateinfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_UpdateinfoActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Updateinfo);
        jButton_Updateinfo.setBounds(200, 350, 220, 80);

        jButton_Patient.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_Patient.setIcon(new javax.swing.ImageIcon("C:\\Users\\acer\\OneDrive\\Documents\\NetBeansProjects\\Java Project Picture\\add (5).png")); // NOI18N
        jButton_Patient.setText("   Patient");
        jButton_Patient.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_Patient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_PatientActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Patient);
        jButton_Patient.setBounds(200, 230, 220, 80);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\acer\\OneDrive\\Documents\\NetBeansProjects\\Java Project Picture\\recportal.jpg")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1240, 590);

        jDesktopPane1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1240, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 592, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_LogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_LogoutMouseClicked
        // TODO add your handling code here:
        ReceptionistLoginForm rf= new ReceptionistLoginForm();
        rf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel_LogoutMouseClicked

    private void jButton_AppointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AppointmentActionPerformed
        // TODO add your handling code here:
        Appointment app= new Appointment();
        jDesktopPane1.add(app);
        app.getRMF(this);
        app.setVisible(true);
//        ChooseDoctor cd = new ChooseDoctor();
//        jDesktopPane1.add(cd);
//        cd.getRMF(this);
//        cd.setVisible(true);
    }//GEN-LAST:event_jButton_AppointmentActionPerformed

    private void jButton_MyDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_MyDetailsActionPerformed
        // TODO add your handling code here:
        Connection con = myConnection.getConnection();
        PreparedStatement ps;
        ResultSet rs;
        try {
            String sql="SELECT id,name,address,gender,age,contact,marital,joiningdate,username FROM receptionist WHERE  id='" + repId + "'";;
            ps = con.prepareStatement(sql);
            rs=ps.executeQuery();
            if(rs.next()){
                //                int did;
                ReceptionistDetails rd=new ReceptionistDetails();
                jDesktopPane1.add(rd);
                rd.setVisible(true);
                rd.pack();
                rd.jLabel_Id.setText(rs.getString("id"));
                rd.jLabel_dName.setText(rs.getString("name"));
                rd.jLabel_Address.setText(rs.getString("address"));
                rd.jLabel_Gender.setText(rs.getString("gender"));
                rd.jLabel_Age.setText(rs.getString("age"));
                rd.jLabel_Contact.setText(rs.getString("contact"));
                rd.jLabel_Marital.setText(rs.getString("marital"));
                rd.jLabel_Jdate.setText(rs.getString("joiningdate"));
                rd.jLabel_Username.setText(rs.getString("username"));
                //this.dispose();
            }
            else{
                JOptionPane.showMessageDialog(null,"Something went wrong");
            }
        }
        catch(Exception ex){
            System.out.println(ex);
        }
    }//GEN-LAST:event_jButton_MyDetailsActionPerformed

    private void jButton_UpdateinfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_UpdateinfoActionPerformed
        // TODO add your handling code here:
        ReceptionistUpdate ru= new ReceptionistUpdate();
        ru.getMB(this);
        ru.rid=repId;
        jDesktopPane1.add(ru);
        ru.setVisible(true);
        ru.pack();

    }//GEN-LAST:event_jButton_UpdateinfoActionPerformed

    private void jButton_PatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_PatientActionPerformed
        // TODO add your handling code here:
        PatientFormFrame pf= new PatientFormFrame();
        pf.curecpid=repId;
        jDesktopPane1.add(pf);
        pf.setVisible(true);
    }//GEN-LAST:event_jButton_PatientActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReceptionistMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReceptionistMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReceptionistMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReceptionistMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReceptionistMainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Appointment;
    private javax.swing.JButton jButton_MyDetails;
    private javax.swing.JButton jButton_Patient;
    private javax.swing.JButton jButton_Updateinfo;
    public javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel_Logout;
    public javax.swing.JLabel jLabel_User;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
