

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
//package java_contact_mgmt_system;
package org.patientsBA.view;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import javax.swing.JFrame;
import java.sql.*;
import org.patientsBA.util.myConnection;
import javax.swing.JOptionPane;

/**
 *
 * @author Raj Cassette
 */
public class SignUpForm extends javax.swing.JFrame {

    /**
     * Creates new form SignUpForm
     */
    String imagePth= null;
    public SignUpForm() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel2 = new javax.swing.JPanel();
        jLabel_User = new javax.swing.JLabel();
        jLabel_Pass = new javax.swing.JLabel();
        jTextFieldUser = new javax.swing.JTextField();
        jPasswordFieldPass = new javax.swing.JPasswordField();
        jButtonCreateAc = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jLabelLogin = new javax.swing.JLabel();
        jLabel_User1 = new javax.swing.JLabel();
        jTextFieldLastname = new javax.swing.JTextField();
        jLabel_User2 = new javax.swing.JLabel();
        jTextFieldFirstname = new javax.swing.JTextField();
        jLabel_Pass1 = new javax.swing.JLabel();
        jPasswordFieldRepass = new javax.swing.JPasswordField();
        jLabel_Pass2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sign Up Form");

        jPanel2.setBackground(new java.awt.Color(44, 32, 80));
        jPanel2.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel_User.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel_User.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_User.setText("First Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(31, 34, 0, 0);
        jPanel2.add(jLabel_User, gridBagConstraints);

        jLabel_Pass.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel_Pass.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Pass.setText("Password");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 34, 0, 0);
        jPanel2.add(jLabel_Pass, gridBagConstraints);

        jTextFieldUser.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUserActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 144;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 18, 0, 0);
        jPanel2.add(jTextFieldUser, gridBagConstraints);

        jPasswordFieldPass.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPasswordFieldPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldPassActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 144;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 18, 0, 0);
        jPanel2.add(jPasswordFieldPass, gridBagConstraints);

        jButtonCreateAc.setBackground(new java.awt.Color(0, 51, 255));
        jButtonCreateAc.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButtonCreateAc.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCreateAc.setText("Create");
        jButtonCreateAc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreateAcActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 18, 0, 0);
        jPanel2.add(jButtonCreateAc, gridBagConstraints);

        jButtonCancel.setBackground(new java.awt.Color(255, 0, 0));
        jButtonCancel.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButtonCancel.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 6, 0, 0);
        jPanel2.add(jButtonCancel, gridBagConstraints);

        jLabelLogin.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabelLogin.setForeground(new java.awt.Color(240, 240, 240));
        jLabelLogin.setText("Already have an account? Click here to login");
        jLabelLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelLoginMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.gridwidth = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(31, 84, 59, 66);
        jPanel2.add(jLabelLogin, gridBagConstraints);

        jLabel_User1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel_User1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_User1.setText("Last Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 34, 0, 0);
        jPanel2.add(jLabel_User1, gridBagConstraints);

        jTextFieldLastname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldLastname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldLastnameActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 144;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 18, 0, 0);
        jPanel2.add(jTextFieldLastname, gridBagConstraints);

        jLabel_User2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel_User2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_User2.setText("Username");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 34, 0, 0);
        jPanel2.add(jLabel_User2, gridBagConstraints);

        jTextFieldFirstname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldFirstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFirstnameActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 144;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(31, 18, 0, 0);
        jPanel2.add(jTextFieldFirstname, gridBagConstraints);

        jLabel_Pass1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel_Pass1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Pass1.setText("ReType Pass");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 34, 0, 0);
        jPanel2.add(jLabel_Pass1, gridBagConstraints);

        jPasswordFieldRepass.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPasswordFieldRepass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldRepassActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 144;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 18, 0, 0);
        jPanel2.add(jPasswordFieldRepass, gridBagConstraints);

        jLabel_Pass2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel_Pass2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Pass2.setText("UserType");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 34, 0, 0);
        jPanel2.add(jLabel_Pass2, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("SignUp Form");
        jLabel1.setAlignmentX(0.5F);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 9;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(38, 88, 0, 0);
        jPanel2.add(jLabel1, gridBagConstraints);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Receptionist" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 66;
        gridBagConstraints.ipady = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 18, 0, 0);
        jPanel2.add(jComboBox1, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUserActionPerformed

    private void jPasswordFieldPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldPassActionPerformed

    private void jLabelLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLoginMouseClicked
        // TODO add your handling code here:
        AdminLoginForm lf = new AdminLoginForm();
        lf.setVisible(true);
        lf.pack();
        lf.setLocationRelativeTo(null);
        lf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabelLoginMouseClicked

    private void jTextFieldLastnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldLastnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldLastnameActionPerformed

    private void jTextFieldFirstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFirstnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFirstnameActionPerformed

    private void jPasswordFieldRepassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldRepassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldRepassActionPerformed

    public boolean isUsernameExist(String un){
         
        boolean uExist=false;
        Connection con = myConnection.getConnection();
        PreparedStatement ps;
        ResultSet rs;
        try {
             String sql="select * from user where username = ?";
            ps = con.prepareStatement(sql);
            ps.setString(1,jTextFieldUser.getText());      
            rs=ps.executeQuery();
            if(rs.next()){
                uExist=true;
            }
        }
           catch(Exception ex){
            System.out.println(ex);
    }
        return uExist;
    }
    
//    public ImageIcon resizePic(String picPath){
//        ImageIcon myImg = new ImageIcon(picPath);
//        Image img = myImg.getImage().getScaledInstance(jLabelPic.getWidth(),jLabelPic.getHeight(),Image.SCALE_SMOOTH);
//        ImageIcon myPicture = new ImageIcon(img);
//        return myPicture;
//    }
    
    
    public boolean verifData(){
        
        // check firstname lastname username password
        if(jTextFieldFirstname.getText().equals("") && jTextFieldLastname.getText().equals("")
                || jTextFieldUser.getText().equals("") || String.valueOf(jPasswordFieldPass.getPassword()).equals(""))
        {
            JOptionPane.showMessageDialog(null,"One or more fields are empty");
        return false;
        }
        
        //check password confirmation
        else if(!String.valueOf(jPasswordFieldPass.getPassword()).equals(String.valueOf(jPasswordFieldRepass.getPassword()))){
               JOptionPane.showMessageDialog(null,"Incorrect Password");
            return false;
        }
        
        //check img path
        else if(imagePth == null){
               JOptionPane.showMessageDialog(null,"Image is not selected");
            return false;      
        }
        else{
        return true;
    }
    }
    private void jButtonCreateAcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreateAcActionPerformed
        // TODO add your handling code here:
        if(verifData()){
        Connection con = myConnection.getConnection();
        PreparedStatement ps;
        try {
             String sql="insert into user(fname,lname,username,pass,pic) values(?,?,?,?,?)";
            ps = con.prepareStatement(sql);
           // ps = con.prepareStatement("INSERT INTO 'user'('fname','lname','username','pass','pic') VALUES (?,?,?,?,?)");
            ps.setString(1,jTextFieldFirstname.getText());
            ps.setString(2,jTextFieldLastname.getText());
            ps.setString(3,jTextFieldUser.getText());
            ps.setString(4,String.valueOf(jPasswordFieldPass.getPassword()));
            
            InputStream img= new FileInputStream(new File(imagePth));
            ps.setBlob(5,img);
            
            if(isUsernameExist(jTextFieldUser.getText())){
                 JOptionPane.showMessageDialog(null,"Username already exist");
            }
            else{
                if(ps.executeUpdate() != 0){
                JOptionPane.showMessageDialog(null,"Account Created");
                
                }
                else{
                JOptionPane.showMessageDialog(null,"Something is wrong");
                }
            }
        }
        catch(Exception ex){
            System.out.println(ex);
    }
    }
    }//GEN-LAST:event_jButtonCreateAcActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButtonCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUpForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUpForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUpForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUpForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */ 
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUpForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonCreateAc;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelLogin;
    private javax.swing.JLabel jLabel_Pass;
    private javax.swing.JLabel jLabel_Pass1;
    private javax.swing.JLabel jLabel_Pass2;
    private javax.swing.JLabel jLabel_User;
    private javax.swing.JLabel jLabel_User1;
    private javax.swing.JLabel jLabel_User2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordFieldPass;
    private javax.swing.JPasswordField jPasswordFieldRepass;
    private javax.swing.JTextField jTextFieldFirstname;
    private javax.swing.JTextField jTextFieldLastname;
    private javax.swing.JTextField jTextFieldUser;
    // End of variables declaration//GEN-END:variables
}
